# Generated by Django 5.2 on 2025-06-08 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical_support', 'Technical Support'), ('billing', 'Billing & Pricing'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('partnership', 'Partnership Inquiry'), ('general', 'General Question'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.TextField(default='123 Tech Hub Drive\nSuite 456\nSan Francisco, CA 94107\nUnited States')),
                ('office_phone', models.CharField(default='+1 (555) SMALL-PDF', max_length=20)),
                ('office_email', models.EmailField(default='support@smallpdf.us', max_length=254)),
                ('business_hours_weekdays', models.CharField(default='Monday - Friday: 9:00 AM - 6:00 PM (EST)', max_length=50)),
                ('business_hours_saturday', models.CharField(default='Saturday: 10:00 AM - 4:00 PM (EST)', max_length=50)),
                ('business_hours_sunday', models.CharField(default='Sunday: Closed', max_length=50)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('auto_response_enabled', models.BooleanField(default=True)),
                ('response_time_hours', models.IntegerField(default=4, help_text='Expected response time in hours')),
                ('admin_notification_enabled', models.BooleanField(default=True)),
                ('admin_email', models.EmailField(default='admin@smallpdf.us', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='PDFTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('tool_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_tools.pdftool')),
            ],
        ),
    ]
