# Generated by Django 5.2 on 2025-06-19 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0003_systemmetrics_errorlog_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Error Log', 'verbose_name_plural': 'Error Logs'},
        ),
        migrations.AlterModelOptions(
            name='pdftool',
            options={'ordering': ['order', 'name'], 'verbose_name': 'PDF Tool', 'verbose_name_plural': 'PDF Tools'},
        ),
        migrations.AlterModelOptions(
            name='processedfile',
            options={'ordering': ['-processed_at'], 'verbose_name': 'Processed File', 'verbose_name_plural': 'Processed Files'},
        ),
        migrations.AlterModelOptions(
            name='systemmetrics',
            options={'ordering': ['-timestamp'], 'verbose_name': 'System Metrics', 'verbose_name_plural': 'System Metrics'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='admin_notification_enabled',
            field=models.BooleanField(default=True, help_text='Send email notifications to admins for new messages'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='auto_response_enabled',
            field=models.BooleanField(default=True, help_text='Send automatic response emails to users'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='business_hours_saturday',
            field=models.CharField(default='Saturday: 10:00 AM - 4:00 PM (IST)', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='business_hours_weekdays',
            field=models.CharField(default='Monday - Friday: 9:00 AM - 6:00 PM (IST)', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='office_address',
            field=models.TextField(default='123 Tech Hub Drive\nSuite 456\nSan Francisco, CA 94107\nUnited States', help_text='Full office address with line breaks'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='response_time_hours',
            field=models.IntegerField(default=4, help_text='Expected response time in hours'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='active_sessions',
            field=models.IntegerField(help_text='Number of active user sessions'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='avg_response_time',
            field=models.FloatField(help_text='Average response time in milliseconds'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='cpu_usage',
            field=models.FloatField(help_text='CPU usage percentage'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='disk_usage',
            field=models.FloatField(help_text='Disk usage percentage'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='error_rate',
            field=models.FloatField(help_text='Error rate percentage'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='memory_usage',
            field=models.FloatField(help_text='Memory usage percentage'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='total_requests',
            field=models.IntegerField(help_text='Total requests in the period'),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='uptime',
            field=models.BigIntegerField(help_text='System uptime in seconds'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', 'created_at'], name='pdf_tools_c_status_afa39c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['category', 'created_at'], name='pdf_tools_c_categor_08c050_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['priority', 'created_at'], name='pdf_tools_c_priorit_6b0edd_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='pdf_tools_e_ip_addr_8aa8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['timestamp'], name='pdf_tools_s_timesta_615438_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id', 'created_at'], name='pdf_tools_u_session_99a240_idx'),
        ),
    ]
