"""
Django settings for smallpdf project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=3%3)pp(p7x=7r)cstl_d^+f4bgi(h!+^8-8_7b96#(dx2^dh-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pdf_tools',
    'tailwind',
    'compressor',
    'theme',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pdf_tools.middleware.ActivityTrackingMiddleware',  # Add this line
]


# Admin tracking settings
ADMIN_TRACKING = {
    'ENABLED': True,
    'TRACK_PAGE_VIEWS': True,
    'TRACK_FILE_UPLOADS': True,
    'TRACK_CONVERSIONS': True,
    'TRACK_DOWNLOADS': True,
    'TRACK_ERRORS': True,
    'TRACK_USER_AGENTS': True,
    'TRACK_IP_ADDRESSES': True,
    'REAL_TIME_UPDATES': True,
    'REAL_TIME_UPDATE_INTERVAL': 5,  # seconds
    
    # Data retention settings
    'KEEP_ACTIVITIES_FOR_DAYS': 90,
    'KEEP_ERRORS_FOR_DAYS': 180,
    'ANONYMIZE_IPS_AFTER_DAYS': 30,
    
    # Performance settings
    'MAX_ACTIVITIES_PER_PAGE': 50,
    'MAX_ERRORS_PER_PAGE': 25,
    'MAX_STACK_TRACE_LENGTH': 5000,
    
    # Alert settings
    'ERROR_RATE_THRESHOLD': 5.0,  # Alert if error rate > 5%
    'RESPONSE_TIME_THRESHOLD': 10.0,  # Alert if avg response time > 10s
    'ENABLE_EMAIL_ALERTS': False,  # Set to True in production
    'ALERT_RECIPIENTS': ['admin@smallpdf.us'],
}
# Session configuration for better tracking
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


ROOT_URLCONF = 'smallpdf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smallpdf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
TIME_ZONE = 'Asia/Kolkata'  # Indian Standard Time (IST)
USE_TZ = True

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'smallpdf_admin',
        'TIMEOUT': 300,  # 5 minutes
    }
} if 'redis' in locals() else {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'smallpdf-admin-cache',
    }
}

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery beat schedule for periodic tasks
CELERY_BEAT_SCHEDULE = {
    'cleanup-old-tracking-data': {
        'task': 'pdf_tools.tasks.cleanup_old_tracking_data',
        'schedule': 86400.0,  # Run daily
    },
    'generate-daily-reports': {
        'task': 'pdf_tools.tasks.generate_daily_reports',
        'schedule': 86400.0,  # Run daily
    },
    'check-system-health': {
        'task': 'pdf_tools.tasks.check_system_health',
        'schedule': 300.0,  # Run every 5 minutes
    },
}
# Temporary file settings for PDF processing
TEMP_FILE_DIR = os.path.join(BASE_DIR, 'tmp')
TEMP_FILE_EXPIRY = 60 * 60  # 1 hour in seconds

# Login and auth settings
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'home'

# Site SEO settings
SITE_ID = 1
SITE_NAME = 'SmallPDF.us'
SITE_DOMAIN = 'smallpdf.us'
META_DESCRIPTION = 'Free online PDF tools to merge, split, compress, convert, and edit PDF files. Easy to use with no installation required.'
META_KEYWORDS = 'PDF tools, PDF editor, merge PDF, split PDF, compress PDF, convert PDF, online PDF tools'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Change to your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'manikant007y@gmail.com'  # Your email
EMAIL_HOST_PASSWORD = 'ljbo vowy olkw lwij'  # Your email password or app password

# Email settings for contact form
DEFAULT_FROM_EMAIL = 'manikant007y@gmail.com'
ADMIN_EMAIL = 'manikant007y@gmail.com'  # Where contact form notifications are sent
SITE_URL = 'https://smallpdf.us'  # Your site URL


# Maximum file size for uploads (10MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Security settings for file uploads
FILE_UPLOAD_PERMISSIONS = 0o644
SECURE_FILE_UPLOAD_EXTENSIONS = [
    'pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'
]

# Session settings
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'contact.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'contact': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
